language: go

go:
    - "1.11.5"
git:
    depth: 1
install:
  - sudo apt-get install hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: Huangkai1008/huangkai1008.github.io
    target_branch: master
    email: h1770360848@outlook.com
    name: huangkai1008