language: go

go:
    - "1.11.5"
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
env:
    - GOPROXY=https://goproxy.io/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: Huangkai1008/huangkai1008.github.io
    target_branch: master
    email: h1770360848@outlook.com
    name: huangkai1008