git:
    depth: 1
env:
  global:
    - HUGO_VERSION="0.82.0"
install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    keep-history: true
    github_token: $GITHUB_TOKEN
    edge: true
    on:
        branch: master
    local_dir: public
    repo: Huangkai1008/huangkai1008.github.io
    target_branch: master
    email: h1770360848@outlook.com
    name: huangkai1008